setwd("c:/ds/git/datasciencecoursera/rprogramming/assignment3")
list.files()
outcome <- read.csv("outcome-of-care-measures.csv", colClasses="character")
head(outcome)
outcome[,11] <- as.numeric(outcome[,11])
hist(outcome[,11])
